서점리스트 뷰 작업
yourCozy/cozy-iOS pull request #18
Opened 2020-08-28 11:49 UTC by didwodnr123

활동탭에서 버튼 누르면 넘어가는 서점리스트 뷰 그리기

네비게이션 바 이슈가 남아있음

2020-08-28 14:49 UTC, choidam requested changes

2020-08-28 14:49 UTC, choidam commented on cozy/cozy/Source/ViewControllers/Activity/ActivityTableViewCell.swift
> +        activityPriceLabel.text = activityCellPrice
책방 이름은 두 줄이상 허용이 되도록 변경해주세요! 
뷰 너무 에쁩니다 ㅎㅎㅎ

2020-08-28 14:51 UTC, choidam commented on cozy/cozy/Source/ViewControllers/Activity/ActivityTableViewCell.swift
> +        activityPriceLabel.font = UIFont(name: "NanumSquareRoundB", size: 14)
폰트 외에도 `activityCellBookStoreNameLabel` 은 두 줄 이상도 허용 되도록 변경해 주세요!

2020-08-29 08:24 UTC, merged

2020-08-29 08:33 UTC, didwodnr123 commented on cozy/cozy/Source/ViewControllers/Activity/ActivityTableViewCell.swift
> +        activityPriceLabel.font = UIFont(name: "NanumSquareRoundB", size: 14)
두 줄 이상으로 인스팩터 바에서 설정해놨습니다!

2020-08-29 09:09 UTC, choidam commented on cozy/cozy/Source/ViewControllers/Activity/ActivityTableViewCell.swift
> +        activityPriceLabel.font = UIFont(name: "NanumSquareRoundB", size: 14)
꼼꼼한 사람,,